---
title: "How do archaeologists write about race and inequality? Computational text analysis of 40 years of Society of American Archaeology Annual Meeting Abstracts."
author:
  - Myfirstname Mylastname:
      email: fl@oneplace.edu
      institute: [UofO]
      correspondence: true
  - Yourfirstname Yourlastname:
      email: fl@another.edu
      institute: [UofA]
      correspondence: false
institute:
  - UofO: University of One Place
  - UofA: University of Another Place
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    bookdown::word_document2:
      fig_caption: yes
      reference_docx: "../templates/template.docx" # Insert path for the DOCX file
      pandoc_args:
      - --lua-filter=../templates/scholarly-metadata.lua
      - --lua-filter=../templates/author-info-blocks.lua
      - --lua-filter=../templates/pagebreak.lua
bibliography: references.bib
csl: "../templates/journal-of-archaeological-science.csl" # Insert path for the bib-style
abstract: |
  Text of abstract
keywords: |
  keyword 1; keyword 2; keyword 3
highlights: |
  These are the highlights
---

<!-- This is the format for text comments that will be ignored during renderings. Do not put R code in these comments because it will not be ignored. -->

<!-- With the following code you can access and display values from the yml header above. -->

Keywords: `r rmarkdown::metadata$keywords`

Highlights: `r rmarkdown::metadata$highlights`

<!-- The following code chunk defines some general settings how code chunks should behave. -->

```{r setup, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  comment = "#>",
  fig.path = "../figures/",
  dpi = 300
)
```

<!-- The actual document text starts here: -->

```{r}
source(here::here('analysis/code/001-word-stats-plots.R'))
```
 
```{r}
 source(here::here(analysis/code/002-topic-model.R'))
```
 
```{r}
 source(here::here(analysis/code/003-word-distances-and-similarities.R'))
```
 
```{r}
 source(here::here(analysis/code/004-keyword-in-context.R'))
```
 
```{r}
 source(here::here(analysis/code/005-social-event-correlation.R'))
```


### Colophon

This report was generated on `r Sys.time()` using the following computational environment and dependencies:

```{r colophon, cache = FALSE}
# which R packages and versions?
if ("devtools" %in% installed.packages()) devtools::session_info()
```

The current Git commit details are:

```{r}
# what commit is this file at? 
if ("git2r" %in% installed.packages() & git2r::in_repository(path = ".")) git2r::repository(here::here())  
```
